name: pizza_repository
description: The Repo that handels pizzas
publish_to: 'none'
version: 0.0.1


environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # equatable: ^2.0.5

  # firebase_auth: ^5.3.2
  cloud_firestore: ^5.4.5
  # firebase_storage: ^12.3.5
  # rxdart: ^0.28.0
  # path: ^1.9.1


dev_dependencies:
   flutter_test:
     sdk: flutter
   flutter_lints: ^2.0.0
  
flutter:
  uses-material-design: true
