// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgNQ1SbE9Noc0N3eqn4MoclHsDxDNElEQ',
    appId: '1:634148090351:web:e9b629e47bdd2a9dfcc61a',
    messagingSenderId: '634148090351',
    projectId: 'pizza-delivery-9176e',
    authDomain: 'pizza-delivery-9176e.firebaseapp.com',
    storageBucket: 'pizza-delivery-9176e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApIXtEkT49wHqIFfZLcZOVeI1ZitqHYtc',
    appId: '1:634148090351:android:c27b1604ae2ec958fcc61a',
    messagingSenderId: '634148090351',
    projectId: 'pizza-delivery-9176e',
    storageBucket: 'pizza-delivery-9176e.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgNQ1SbE9Noc0N3eqn4MoclHsDxDNElEQ',
    appId: '1:634148090351:web:afa615619998c36ffcc61a',
    messagingSenderId: '634148090351',
    projectId: 'pizza-delivery-9176e',
    authDomain: 'pizza-delivery-9176e.firebaseapp.com',
    storageBucket: 'pizza-delivery-9176e.firebasestorage.app',
  );

}